name: IPL Tickets Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'  # Enable dependency caching

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run ticket monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        MONITOR_MATCH_IDENTIFIER: ${{ vars.MONITOR_MATCH_IDENTIFIER }}
        MONITOR_URL: ${{ vars.MONITOR_URL }}
        DISTRICT_NOTIFY_STATUSES: ${{ vars.DISTRICT_NOTIFY_STATUSES }}
      run: |
        python .github/workflows/update_config.py
        python main.py

    - name: Save status history
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: status-history-${{ github.run_id }}
        path: status_history.json
        retention-days: 3

    - name: Save logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ github.run_id }}
        path: |
          *.log
          !venv/**/*.log  # Exclude virtualenv logs
        if-no-files-found: warn