name: IPL Ticket Monitor
on:
  schedule:
    # Run every 5 minutes
    - cron: '${{ vars.CRON_SCHEDULE }}'
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run ticket monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        MONITOR_MATCH_IDENTIFIER: ${{ vars.MONITOR_MATCH_IDENTIFIER }}
        MONITOR_URL: ${{ vars.MONITOR_URL }}
        DISTRICT_NOTIFY_STATUSES: ${{ vars.DISTRICT_NOTIFY_STATUSES }}
      run: |
        cd .github/workflows && python update_config.py
        cd ../..
        python main.py

    - name: Save status history
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: status-history
        path: status_history.json

    - name: Save logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: "*.log"
        if-no-files-found: warn